version: "3"

services:
  server:
    image: "go-tcp-pow/server:latest"
    build:
      context: .
      dockerfile: "Dockerfile.server"
    ports:
      - "8000:8000"
    restart: "on-failure"
    networks:
      - "go-tcp-pow"
    depends_on:
      - "redis"
  
  redis:
    image: "redis:7-alpine"
    ports:
      - "6380:6379"
    restart: "on-failure"
    networks:
      - "go-tcp-pow"

networks:
  go-tcp-pow:
    driver: "bridge"
