version: "3"

services:
  server:
    image: "tcp-pow-server:latest"
    build:
      context: .
      dockerfile: "Dockerfile.server"
    ports:
      - "8000:8000"
    restart: "on-failure"
    networks:
      - "tcp-pow"
    depends_on:
      - "redis"
  
  redis:
    image: "redis:7-alpine"
    ports:
      - "6380:6379"
    restart: "on-failure"
    networks:
      - "tcp-pow"

  client:
    image: "tcp-pow-client:latest"
    build:
      context: .
      dockerfile: "Dockerfile.client"
    restart: "on-failure"
    networks:
      - "tcp-pow"
    depends_on:
      - "server"

networks:
  tcp-pow:
    driver: "bridge"
